
import { InvestmentOption } from './types';

export const INITIAL_INVESTMENT_TIERS: InvestmentOption[] = [];

export const NETWORKS = ['Jazz', 'Zong', 'Telenor', 'Ufone'];

export const TRANSLATIONS = {
  ur: {
    home: 'ہوم',
    status: 'اسٹیٹس',
    admin: 'ایڈمن',
    heroTitle: 'تھوڑا انویسٹ کریں، لاکھوں جیتیں!',
    heroSub: 'ہزاروں لوگ پہلے ہی شامل ہو چکے ہیں۔ کیا آپ اپنی قسمت آزمائیں گے؟',
    investOnly: 'انویسٹ کریں صرف',
    winTotal: 'جیتیں پورے',
    members: 'ممبرز',
    liveDraw: 'لائیو قرعہ اندازی',
    joinNow: 'حصہ لیں',
    share: 'شیئر کریں',
    statusTitle: 'آپ کا اکاؤنٹ ڈیش بورڈ',
    statusSub: 'اپنی شمولیت اور سیکرٹ ٹوکن دیکھنے کے لیے تفصیلات درج کریں۔',
    nameLabel: 'مکمل نام (انگریزی)',
    phoneLabel: 'موبائل نمبر (03 سے شروع)',
    networkLabel: 'سم نیٹ ورک',
    searchBtn: 'اکاؤنٹ چیک کریں',
    backHome: 'ہوم پر جائیں',
    regNow: 'رجسٹر کریں',
    approvedMsg: 'منظور شدہ',
    pendingMsg: 'پینڈنگ (زیر غور)',
    rejectedMsg: 'مسترد شدہ',
    successTitle: 'درخواست کامیابی سے جمع ہو گئی!',
    successSub: 'آپ کی درخواست موصول ہو چکی ہے۔ ہم جلد ہی آپ کی فراہم کردہ معلومات کی تصدیق کریں گے۔ تب تک اپنا ٹوکن محفوظ رکھیں!',
    downloadQR: 'کیو آر کوڈ ڈاؤن لوڈ کریں',
    scanOrPay: 'اسکین کریں یا نمبر پر بھیجیں',
    loginSuccess: 'خوش آمدید! آپ کے تمام اکاؤنٹس کی تفصیلات نیچے درج ہیں۔',
    noRecord: 'کوئی ریکارڈ نہیں ملا!',
    agreementHeader: 'قانونی شرائط و ضوابط',
    agree1: 'میں اقرار کرتا ہوں کہ میری عمر 18 سال سے زیادہ ہے اور میں یہ رقم اپنی خوشی سے انویسٹ کر رہا ہوں۔',
    agree2: 'یہ ایک معمولی رقم (مثلاً 10 روپے بچوں کی چاکلیٹ کے برابر) ہے، میں ہارنے کی صورت میں کمپنی پر کوئی کیس یا قانونی کارروائی نہیں کروں گا۔',
    agree3: 'میں جانتا ہوں کہ ممبرز مکمل ہونے پر ہی قرعہ اندازی ہوگی اور میں غلط ٹریکنگ آئی ڈی نہیں دوں گا۔',
    paymentTitle: 'پیمنٹ کا طریقہ',
    paymentSub: 'نیچے دیا گیا کیو آر کوڈ اسکین کریں یا نمبر پر رقم بھیجیں',
    tokenTitle: 'آپ کا مستقل لکی ریکارڈ کوڈ',
    tokenDesc: 'یہ 5 ہندسوں کا کوڈ آپ کے پورے اکاؤنٹ کے لیے صرف ایک بار جاری کیا گیا ہے۔ اسے سنبھال کر رکھیں! آپ اپنی تمام انٹریز کا رزلٹ اور اسٹیٹس اسی ایک کوڈ سے چیک کر سکتے ہیں۔ یہ دوبارہ جاری نہیں ہوگا۔',
    duplicateError: 'آپ اس سروس کے لیے پہلے ہی درخواست دے چکے ہیں۔',
    duplicateTIDError: 'یہ ٹریکنگ آئی ڈی (TID) پہلے ہی استعمال ہو چکی ہے۔ براہ کرم درست آئی ڈی درج کریں۔',
    urduNameError: 'نام صرف انگلش میں لکھیں! اردو میں لکھنا منع ہے۔',
    pendingDetail: 'آپ کی درخواست فی الحال پینڈنگ میں ہے۔ اگر آپ کی فراہم کردہ معلومات (TID وغیرہ) درست ہوئی تو آپ کو انعام کے لیے رجسٹر کر لیا جائے گا۔ اپنا اسٹیٹس چیک کرتے رہیں۔',
    awaitingTIDDetail: 'آپ کی درخواست ابھی مکمل نہیں ہوئی۔ براہ کرم ٹریکنگ آئی ڈی (TID) درج کریں تاکہ ہم آپ کی درخواست پر کارروائی کر سکیں۔',
    welcomeTitle: 'درخواست جمع ہو گئی!',
    welcomeSub: 'آپ کی درخواست کامیابی سے موصول ہو چکی ہے۔ ہماری ٹیم آپ کی فراہم کردہ معلومات کی تصدیق کرے گی، جس کے بعد آپ کو مطلع کر دیا جائے گا۔ تب تک اپنا اسٹیٹس چیک کرتے رہیں۔',
    enterTIDNow: 'TID ابھی درج کریں',
    enterTIDLater: 'بعد میں درج کریں (مائی اسٹیٹس سے)',
    shareText: 'اس کارڈ کو جلد مکمل کرنے کے لیے دوستوں کے ساتھ شیئر کریں تاکہ قرعہ اندازی جلد ہو سکے!',
    back: 'واپس',
    winnersTitle: 'حالیہ خوش نصیب فاتحین',
    winnersSub: 'ان لوگوں نے اپنی قسمت آزمائی اور بڑے انعامات جیتے۔ اگلا نمبر آپ کا ہو سکتا ہے!',
    howItWorksTitle: 'یہ کیسے کام کرتا ہے؟',
    step1Title: 'کارڈ منتخب کریں',
    step1Desc: 'اپنی پسند کی رقم کا کارڈ منتخب کریں (مثلاً 10 یا 20 روپے)۔',
    step2Title: 'رجسٹریشن اور پیمنٹ',
    step2Desc: 'اپنی تفصیلات درج کریں اور دیئے گئے نمبر پر رقم بھیج کر TID لکھیں۔',
    step3Title: 'ٹوکن حاصل کریں',
    step3Desc: 'درخواست منظور ہونے پر آپ کو ایک سیکرٹ ٹوکن ملے گا، اسے محفوظ رکھیں۔',
    step4Title: 'قرعہ اندازی اور رزلٹ',
    step4Desc: 'ممبرز مکمل ہونے پر لائیو قرعہ اندازی ہوگی اور آپ ٹوکن سے رزلٹ چیک کر سکیں گے۔',
    viewResults: 'رزلٹ پورٹل',
    resultTitle: 'رزلٹ پورٹل (قرعہ اندازی کا نتیجہ)',
    resultSub: 'اپنا 5 ہندسوں کا لکی ریکارڈ کوڈ یہاں درج کریں اور اپنا نتیجہ دیکھیں۔',
    checkResultBtn: 'نتیجہ چیک کریں',
    winnerCongrat: 'مبارک ہو! آپ اس قرعہ اندازی کے فاتح ہیں۔ ہم آپ سے جلد رابطہ کریں گے۔',
    notWinner: 'معذرت! اس بار آپ کا نام نہیں نکلا۔ ہمت نہ ہاریں، اگلی بار کوشش کریں!',
    drawPending: 'اس کارڈ کی قرعہ اندازی ابھی پینڈنگ ہے۔ ممبرز مکمل ہونے کا انتظار کریں۔'
  },
  en: {
    home: 'Home',
    status: 'Status',
    admin: 'Admin',
    heroTitle: 'Invest Small, Win Big!',
    heroSub: 'Thousands have joined. Will you try your luck?',
    investOnly: 'Invest Only',
    winTotal: 'Win Total',
    members: 'Members',
    liveDraw: 'Live Draw',
    joinNow: 'Join Now',
    share: 'Share',
    statusTitle: 'Your Account Dashboard',
    statusSub: 'Enter details to see your participation and secret tokens.',
    nameLabel: 'Full Name (English)',
    phoneLabel: 'Mobile Number (Starts with 03)',
    networkLabel: 'Network',
    searchBtn: 'Check Account',
    backHome: 'Back Home',
    regNow: 'Register Now',
    approvedMsg: 'Approved',
    pendingMsg: 'Pending (Under Review)',
    rejectedMsg: 'Rejected',
    successTitle: 'Application Submitted Successfully!',
    successSub: 'Your application has been received. We will verify your details shortly. Keep your token safe until then!',
    downloadQR: 'Download QR Code',
    scanOrPay: 'Scan or Pay via Number',
    loginSuccess: 'Welcome back! All your account entries are listed below.',
    noRecord: 'No record found!',
    agreementHeader: 'Legal Terms & Conditions',
    agree1: 'I declare that I am 18+ and participating of my own free will.',
    agree2: 'This is a small amount (like 10 Rs for a snack); I will not file any legal case if I do not win.',
    agree3: 'I understand the draw happens after members are full and I won\'t use fake TIDs.',
    paymentTitle: 'Payment Method',
    paymentSub: 'Scan the QR code below or send to the number',
    tokenTitle: 'Your Permanent Lucky Record Code',
    tokenDesc: 'This 5-digit code is issued only once for your entire account. Keep it safe! You can check the results and status of all your entries with this single code. It will not be reissued.',
    duplicateError: 'You have already applied for this service.',
    duplicateTIDError: 'This Tracking ID (TID) has already been used. Please enter a valid ID.',
    urduNameError: 'Write your name in English only! Urdu is not allowed.',
    pendingDetail: 'Your request is currently pending. If your info (TID, etc.) is correct, you will be fully registered. Keep checking status.',
    awaitingTIDDetail: 'Your request is incomplete. Please enter the Tracking ID (TID) so we can process your application.',
    welcomeTitle: 'Application Submitted!',
    welcomeSub: 'Your application has been received successfully. Our team will verify your information, after which you will be notified. Keep checking your status until then.',
    enterTIDNow: 'Enter TID Now',
    enterTIDLater: 'Enter Later (from My Status)',
    shareText: 'Share this card with friends to complete it faster for an early draw!',
    back: 'Back',
    winnersTitle: 'Recent Lucky Winners',
    winnersSub: 'These people tried their luck and won big prizes. You could be next!',
    howItWorksTitle: 'How It Works?',
    step1Title: 'Select a Card',
    step1Desc: 'Choose a card with your preferred investment (e.g., Rs. 10 or 20).',
    step2Title: 'Register & Pay',
    step2Desc: 'Enter your details, send payment to the number, and enter TID.',
    step3Title: 'Get Your Token',
    step3Desc: 'Once approved, you will receive a secret token. Keep it safe.',
    step4Title: 'Draw & Results',
    step4Desc: 'Live draw happens when members are full. Check results via token.',
    viewResults: 'Result Portal',
    resultTitle: 'Result Portal (Draw Results)',
    resultSub: 'Enter your 5-digit lucky record code here to see your result.',
    checkResultBtn: 'Check Result',
    winnerCongrat: 'Congratulations! You are the winner of this draw. We will contact you soon.',
    notWinner: 'Sorry! You didn\'t win this time. Don\'t lose hope, try again next time!',
    drawPending: 'The draw for this card is still pending. Wait for members to be full.'
  }
};
